version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Dockerfile
    depends_on:
      - mongo   
  mongo:
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --auth --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=T0121
    ports:
      - "27017:27017"
    restart: always
 
 

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"   
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root   
      ME_CONFIG_MONGODB_ADMINPASSWORD: T0121
      ME_CONFIG_MONGODB_URL: mongodb://root:T0121@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongodb-data:
    driver: local